exclude: 'thirdParty'
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v12.0.1
  hooks:
  - id: clang-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: no-commit-to-branch
    args: [-b, dev]
  - id: check-merge-conflict
  - id: trailing-whitespace
    exclude_types: [markdown, rst]
