exclude: 'thirdParty'
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v12.0.1
  hooks:
  - id: clang-format
    types_or: [file]
    files: \.(cpp|def|h|cu|tpp|kernel|loader|unitless|hpp|param)$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: no-commit-to-branch
    args: [-b, dev]
  - id: check-merge-conflict
  - id: trailing-whitespace
    exclude_types: [markdown, rst]
  - id: end-of-file-fixer
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: [--extend-ignore, E203, --max-line-length, "120"]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.12.1
  hooks:
  - id: black
    args: [-l, "120"]
