exclude: 'thirdParty'
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v12.0.1
  hooks:
  - id: clang-format
    types_or: [file]
    files: \.(cpp|def|h|cu|tpp|kernel|loader|unitless|hpp|param)$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: no-commit-to-branch
    args: [-b, dev]
  - id: check-merge-conflict
  - id: trailing-whitespace
    exclude_types: [markdown, rst]
  - id: end-of-file-fixer
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    # black's recommendation on compatibility with flake8
    # see https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8
    args: [--extend-ignore, E203, --max-line-length, "120"]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.12.1
  hooks:
  - id: black
    args: [-l, "120"]
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
    - id: forbid-tabs
      types_or: [file]
      exclude_types: [rst, tex, tsv]
    - id: remove-tabs
      types_or: [file]
      exclude_types: [rst, tex, tsv]
    - id: forbid-crlf
    - id: remove-crlf
- repo: https://github.com/brutus/enforce-ascii
  rev: v0.2.1
  hooks:
      - id: enforce-ascii
        types_or: [file]
        exclude_types: [rst, tex, tsv, jupyter, markdown]
        exclude: .zenodo.json
